=== openbmc/openpower-libhei/chip_data/schema/chip-data-schema-v01.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Chip Data Schema",
    "version": 1,
    "type": "object",
    "required": ["version", "model_ec"],
    "additionalProperties": false,
    "properties": {
        "version": {
            "type": "integer",
            "minimum": 1,
            "maximum": 1
        },
        "model_ec": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": { "$ref": "#/$defs/model_ec" }
        },
        "registers": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^\\w+$": { "$ref": "#/$defs/register" }
            }
        },
        "isolation_nodes": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^\\w+$": { "$ref": "#/$defs/isolation_node" }
            }
        },
        "root_nodes": {
            "type": "object",
            "propertyNames": { "$ref": "#/$defs/attn_type" },
            "patternProperties": {
                "": { "$ref": "#/$defs/root_node" }
            }
        },
        "capture_groups": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^\\w+$": {
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": { "$ref": "#/$defs/capture_register" }
                }
            }
        }
    },
    "$defs": {
        "name": {
            "type": "string",
            "pattern": "^\\w+$"
        },
        "instance": {
            "type": "integer",
            "minimum": 0
        },
        "instance_array": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": { "$ref": "#/$defs/instance" }
        },
        "instance_map": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[0-9]+$": { "$ref": "#/$defs/instance" }
            }
        },
        "hex_string": {
            "type": "string",
            "pattern": "^0x([0-9a-fA-F]{8}){1,2}$"
        },
        "model_ec": {
            "type": "string",
            "enum": [
                "P10_10",
                "P10_20",
                "EXPLORER_11",
                "EXPLORER_20",
                "ODYSSEY_10",
                "P11S_10",
                "P11T_10"
            ]
        },
        "attn_type": {
            "type": "string",
            "enum": ["CS", "UCS", "RE", "SPA", "HA"]
        },
        "reg_type": {
            "type": "string",
            "enum": ["SCOM", "IDSCOM"]
        },
        "access_type": {
            "type": "string",
            "enum": ["RO", "WO", "RW"]
        },
        "register": {
            "type": "object",
            "required": ["instances"],
            "additionalProperties": false,
            "properties": {
                "reg_type": { "$ref": "#/$defs/reg_type" },
                "access": { "$ref": "#/$defs/access_type" },
                "instances": {
                    "type": "object",
                    "additionalProperties": false,
                    "patternProperties": {
                        "^[0-9]+$": { "$ref": "#/$defs/hex_string" }
                    }
                }
            }
        },
        "isolation_node": {
            "type": "object",
            "required": ["instances", "rules", "bits"],
            "additionalProperties": false,
            "properties": {
                "reg_type": { "$ref": "#/$defs/reg_type" },
                "instances": { "$ref": "#/$defs/instance_array" },
                "rules": {
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": { "$ref": "#/$defs/isolation_rule" }
                },
                "bits": {
                    "type": "object",
                    "additionalProperties": false,
                    "patternProperties": {
                        "^[0-9]+(:[0-9]+)?$": {
                            "$ref": "#/$defs/isolation_bit"
                        }
                    }
                },
                "capture_groups": {
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": { "$ref": "#/$defs/capture_group" }
                }
            }
        },
        "isolation_rule": {
            "type": "object",
            "required": ["attn_type", "node_inst", "expr"],
            "additionalProperties": false,
            "properties": {
                "attn_type": {
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": { "$ref": "#/$defs/attn_type" }
                },
                "node_inst": { "$ref": "#/$defs/instance_array" },
                "expr": { "$ref": "#/$defs/isolation_rule_expression" }
            }
        },
        "isolation_rule_expression": {
            "type": "object",
            "required": ["expr_type"],
            "properties": {
                "expr_type": {
                    "type": "string",
                    "enum": [
                        "reg",
                        "int",
                        "and",
                        "or",
                        "not",
                        "lshift",
                        "rshift"
                    ]
                },
                "reg_name": { "$ref": "#/$defs/name" },
                "reg_inst": { "$ref": "#/$defs/instance_map" },
                "int_value": { "$ref": "#/$defs/hex_string" },
                "expr": { "$ref": "#/$defs/isolation_rule_expression" },
                "exprs": {
                    "type": "array",
                    "minItems": 2,
                    "items": { "$ref": "#/$defs/isolation_rule_expression" }
                },
                "shift_value": {
                    "type": "integer",
                    "minimum": 0
                }
            },
            "allOf": [
                {
                    "if": { "properties": { "expr_type": { "const": "reg" } } },
                    "then": {
                        "required": ["reg_name"],
                        "not": {
                            "required": [
                                "int_value",
                                "shift_value",
                                "expr",
                                "exprs"
                            ]
                        }
                    }
                },
                {
                    "if": { "properties": { "expr_type": { "const": "int" } } },
                    "then": {
                        "required": ["int_value"],
                        "not": {
                            "required": [
                                "reg_name",
                                "reg_inst",
                                "shift_value",
                                "expr",
                                "exprs"
                            ]
                        }
                    }
                },
                {
                    "if": {
                        "properties": {
                            "expr_type": { "enum": ["and", "or"] }
                        }
                    },
                    "then": {
                        "required": ["exprs"],
                        "not": {
                            "required": [
                                "reg_name",
                                "reg_inst",
                                "int_value",
                                "shift_value",
                                "expr"
                            ]
                        }
                    }
                },
                {
                    "if": { "properties": { "expr_type": { "const": "not" } } },
                    "then": {
                        "required": ["expr"],
                        "not": {
                            "required": [
                                "reg_name",
                                "reg_inst",
                                "int_value",
                                "shift_value",
                                "exprs"
                            ]
                        }
                    }
                },
                {
                    "if": {
                        "properties": {
                            "expr_type": { "enum": ["lshift", "rshift"] }
                        }
                    },
                    "then": {
                        "required": ["expr", "shift_value"],
                        "not": {
                            "required": [
                                "reg_name",
                                "reg_inst",
                                "int_value",
                                "exprs"
                            ]
                        }
                    }
                }
            ]
        },
        "isolation_bit": {
            "type": "object",
            "required": ["desc"],
            "additionalProperties": false,
            "properties": {
                "desc": {
                    "type": "string"
                },
                "child_node": {
                    "type": "object",
                    "required": ["name"],
                    "additionalProperties": false,
                    "properties": {
                        "name": { "$ref": "#/$defs/name" },
                        "inst": { "$ref": "#/$defs/instance_map" }
                    }
                },
                "capture_groups": {
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": { "$ref": "#/$defs/capture_group" }
                }
            }
        },
        "capture_group": {
            "type": "object",
            "required": ["group_name", "group_inst"],
            "additionalProperties": false,
            "properties": {
                "group_name": { "$ref": "#/$defs/name" },
                "group_inst": { "$ref": "#/$defs/instance_map" }
            }
        },
        "root_node": {
            "type": "object",
            "required": ["name", "inst"],
            "additionalProperties": false,
            "properties": {
                "name": { "$ref": "#/$defs/name" },
                "inst": { "$ref": "#/$defs/instance" }
            }
        },
        "capture_register": {
            "type": "object",
            "required": ["reg_name", "reg_inst"],
            "additionalProperties": false,
            "properties": {
                "reg_name": { "$ref": "#/$defs/name" },
                "reg_inst": { "$ref": "#/$defs/instance_map" }
            }
        }
    }
}

=== openbmc/openpower-libhei/chip_data/p10_10/node_nx_cq_fir.json
{
    "version": 1,
    "model_ec": ["P10_10"],
    "registers": {
        "NX_CQ_FIR": {
            "instances": {
                "0": "0x02011080"
            }
        },
        "NX_CQ_FIR_MASK": {
            "instances": {
                "0": "0x02011083"
            }
        },
        "NX_CQ_FIR_ACT0": {
            "instances": {
                "0": "0x02011086"
            }
        },
        "NX_CQ_FIR_ACT1": {
            "instances": {
                "0": "0x02011087"
            }
        },
        "NX_CQ_FIR_WOF": {
            "instances": {
                "0": "0x02011088"
            }
        }
    },
    "isolation_nodes": {
        "NX_CQ_FIR": {
            "instances": [0],
            "rules": [
                {
                    "attn_type": ["CHIP_CS"],
                    "node_inst": [0],
                    "expr": {
                        "expr_type": "and",
                        "exprs": [
                            {
                                "expr_type": "reg",
                                "reg_name": "NX_CQ_FIR"
                            },
                            {
                                "expr_type": "not",
                                "expr": {
                                    "expr_type": "reg",
                                    "reg_name": "NX_CQ_FIR_MASK"
                                }
                            },
                            {
                                "expr_type": "not",
                                "expr": {
                                    "expr_type": "reg",
                                    "reg_name": "NX_CQ_FIR_ACT0"
                                }
                            },
                            {
                                "expr_type": "not",
                                "expr": {
                                    "expr_type": "reg",
                                    "reg_name": "NX_CQ_FIR_ACT1"
                                }
                            }
                        ]
                    }
                },
                {
                    "attn_type": ["RECOV"],
                    "node_inst": [0],
                    "expr": {
                        "expr_type": "and",
                        "exprs": [
                            {
                                "expr_type": "reg",
                                "reg_name": "NX_CQ_FIR"
                            },
                            {
                                "expr_type": "not",
                                "expr": {
                                    "expr_type": "reg",
                                    "reg_name": "NX_CQ_FIR_MASK"
                                }
                            },
                            {
                                "expr_type": "not",
                                "expr": {
                                    "expr_type": "reg",
                                    "reg_name": "NX_CQ_FIR_ACT0"
                                }
                            },
                            {
                                "expr_type": "reg",
                                "reg_name": "NX_CQ_FIR_ACT1"
                            }
                        ]
                    }
                },
                {
                    "attn_type": ["UNIT_CS"],
                    "node_inst": [0],
                    "expr": {
                        "expr_type": "and",
                        "exprs": [
                            {
                                "expr_type": "reg",
                                "reg_name": "NX_CQ_FIR"
                            },
                            {
                                "expr_type": "not",
                                "expr": {
                                    "expr_type": "reg",
                                    "reg_name": "NX_CQ_FIR_MASK"
                                }
                            },
                            {
                                "expr_type": "reg",
                                "reg_name": "NX_CQ_FIR_ACT0"
                            },
                            {
                                "expr_type": "reg",
                                "reg_name": "NX_CQ_FIR_ACT1"
                            }
                        ]
                    }
                }
            ],
            "bits": {
                "0": {
                    "desc": "PBI internal parity error"
                },
                "1": {
                    "desc": "PowerBus CE error"
                },
                "2": {
                    "desc": "PowerBus UE error"
                },
                "3": {
                    "desc": "PowerBus SUE error"
                },
                "4": {
                    "desc": "Inbound array CE error"
                },
                "5": {
                    "desc": "Inbound array UE error"
                },
                "6": {
                    "desc": "Paste request rejected"
                },
                "7": {
                    "desc": "PowerBus command hang error"
                },
                "8": {
                    "desc": "PowerBus read address error"
                },
                "9": {
                    "desc": "PowerBus write address error"
                },
                "10": {
                    "desc": "PowerBus miscellaneous error"
                },
                "11": {
                    "desc": "MMIO BAR parity error"
                },
                "12": {
                    "desc": "UMAC detected SUE on WC Interrupt"
                },
                "13": {
                    "desc": "ACK_DEAD cresp received by read command"
                },
                "14": {
                    "desc": "ACK_DEAD cresp received by write command"
                },
                "15": {
                    "desc": "Reserved. Used to be PowerBus Link Abort in P9"
                },
                "16": {
                    "desc": "Hang poll time expired on internal transfer"
                },
                "17": {
                    "desc": "Parity error on ERAT arrays"
                },
                "18": {
                    "desc": "Correctable error on ERAT arrays"
                },
                "19": {
                    "desc": "Uncorrectable error on ERAT arrays"
                },
                "20": {
                    "desc": "Special uncorrectable error on ERAT arrays"
                },
                "21": {
                    "desc": "Hang on checkin/checkout request to NMMU"
                },
                "22": {
                    "desc": "ERAT control logic error"
                },
                "23": {
                    "desc": "Uncorrectable error on the Powerbus data for xlate"
                },
                "24": {
                    "desc": "Special uncorrectable error on the Powerbus data for xlate"
                },
                "25": {
                    "desc": "ACK_DEAD cresp received by UMAC read command"
                },
                "26": {
                    "desc": "Link check aborted while waiting on UMAC data"
                },
                "27": {
                    "desc": "Uncorrectable error on CRB QW0/4"
                },
                "28": {
                    "desc": "Special uncorrectable error on CRB QW0/4"
                },
                "29": {
                    "desc": "UMAC has detected a control logic error"
                },
                "30": {
                    "desc": "Other SCOM satellite parity error"
                },
                "31": {
                    "desc": "SCOM write to RNG when not allowed"
                },
                "32": {
                    "desc": "A first noise source in the RNG has failed"
                },
                "33": {
                    "desc": "A second noise source in the RNG has failed"
                },
                "34": {
                    "desc": "RNG has detected a control logic error"
                },
                "35": {
                    "desc": "NMMU has signaled local checkstop"
                },
                "36": {
                    "desc": "VAS has signaled local checkstop"
                },
                "37": {
                    "desc": "PBCQ has detected a control logic error"
                },
                "38": {
                    "desc": "PBCQ has detected a failed link on an interrupt"
                },
                "39": {
                    "desc": "UMAC has detected an SUE on interrupt address"
                },
                "40": {
                    "desc": "SMF error"
                },
                "41": {
                    "desc": "Topology index error detected in NX"
                }
            },
            "capture_groups": [
                {
                    "group_name": "NX_CQ_FIR",
                    "group_inst": {
                        "0": 0
                    }
                }
            ]
        }
    }
}

=== openbmc/openpower-libhei/chip_data/p10_20/node_nmmu_cq_fir.json
{
    "version": 1,
    "model_ec": ["P10_20"],
    "registers": {
        "NMMU_CQ_FIR": {
            "instances": {
                "0": "0x02010C00",
                "1": "0x03010C00"
            }
        },
        "NMMU_CQ_FIR_MASK": {
            "instances": {
                "0": "0x02010C03",
                "1": "0x03010C03"
            }
        },
        "NMMU_CQ_FIR_ACT0": {
            "instances": {
                "0": "0x02010C06",
                "1": "0x03010C06"
            }
        },
        "NMMU_CQ_FIR_ACT1": {
            "instances": {
                "0": "0x02010C07",
                "1": "0x03010C07"
            }
        },
        "NMMU_CQ_FIR_WOF": {
            "instances": {
                "0": "0x02010C08",
                "1": "0x03010C08"
            }
        }
    },
    "isolation_nodes": {
        "NMMU_CQ_FIR": {
            "instances": [0, 1],
            "rules": [
                {
                    "attn_type": ["CS"],
                    "node_inst": [0, 1],
                    "expr": {
                        "expr_type": "and",
                        "exprs": [
                            {
                                "expr_type": "reg",
                                "reg_name": "NMMU_CQ_FIR"
                            },
                            {
                                "expr_type": "not",
                                "expr": {
                                    "expr_type": "reg",
                                    "reg_name": "NMMU_CQ_FIR_MASK"
                                }
                            },
                            {
                                "expr_type": "not",
                                "expr": {
                                    "expr_type": "reg",
                                    "reg_name": "NMMU_CQ_FIR_ACT0"
                                }
                            },
                            {
                                "expr_type": "not",
                                "expr": {
                                    "expr_type": "reg",
                                    "reg_name": "NMMU_CQ_FIR_ACT1"
                                }
                            }
                        ]
                    }
                },
                {
                    "attn_type": ["RE"],
                    "node_inst": [0, 1],
                    "expr": {
                        "expr_type": "and",
                        "exprs": [
                            {
                                "expr_type": "reg",
                                "reg_name": "NMMU_CQ_FIR"
                            },
                            {
                                "expr_type": "not",
                                "expr": {
                                    "expr_type": "reg",
                                    "reg_name": "NMMU_CQ_FIR_MASK"
                                }
                            },
                            {
                                "expr_type": "not",
                                "expr": {
                                    "expr_type": "reg",
                                    "reg_name": "NMMU_CQ_FIR_ACT0"
                                }
                            },
                            {
                                "expr_type": "reg",
                                "reg_name": "NMMU_CQ_FIR_ACT1"
                            }
                        ]
                    }
                },
                {
                    "attn_type": ["UCS"],
                    "node_inst": [0, 1],
                    "expr": {
                        "expr_type": "and",
                        "exprs": [
                            {
                                "expr_type": "reg",
                                "reg_name": "NMMU_CQ_FIR"
                            },
                            {
                                "expr_type": "not",
                                "expr": {
                                    "expr_type": "reg",
                                    "reg_name": "NMMU_CQ_FIR_MASK"
                                }
                            },
                            {
                                "expr_type": "reg",
                                "reg_name": "NMMU_CQ_FIR_ACT0"
                            },
                            {
                                "expr_type": "reg",
                                "reg_name": "NMMU_CQ_FIR_ACT1"
                            }
                        ]
                    }
                }
            ],
            "bits": {
                "0": {
                    "desc": "PBI internal parity error"
                },
                "1": {
                    "desc": "PowerBus command hang error"
                },
                "2": {
                    "desc": "PowerBus read address error"
                },
                "3": {
                    "desc": "PowerBus write address error"
                },
                "4": {
                    "desc": "PowerBus miscellaneous error"
                },
                "5": {
                    "desc": "Reserved"
                },
                "6": {
                    "desc": "PowerBus Xlate UE error"
                },
                "7": {
                    "desc": "PowerBus Xlate SUE error"
                },
                "8": {
                    "desc": "PowerBus CE error"
                },
                "9": {
                    "desc": "PowerBus UE error"
                },
                "10": {
                    "desc": "PowerBus SUE error"
                },
                "11": {
                    "desc": "Inbound LCO_ARRAY CE error"
                },
                "12": {
                    "desc": "Inbound LCO_ARRAY UE error"
                },
                "13": {
                    "desc": "Inbound LCO_ARRAY SUE error"
                },
                "14": {
                    "desc": "Inbound array CE error"
                },
                "15": {
                    "desc": "Inbound array UE error"
                },
                "16": {
                    "desc": "internal state error"
                },
                "17": {
                    "desc": "ACK_DEAD cresp received by read command"
                },
                "18": {
                    "desc": "ACK_DEAD cresp received by write command"
                },
                "19": {
                    "desc": "Link check aborted while waiting on data"
                }
            },
            "capture_groups": [
                {
                    "group_name": "NMMU_CQ_FIR",
                    "group_inst": {
                        "0": 0,
                        "1": 1
                    }
                }
            ]
        }
    }
}
